name: blastocyst-if
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - scikit-image
  - scipy
  - tifffile
  - pip:
      - cellpose>=4.0
      - napari[all]
      - bioio
      - bioio-czi
      - bioio-lif
      - bioio-ome-tiff
      - bioio-tifffile
